### ISSUE TITLE
MS SQL adapter

### ISSUE THREAD

**Issue by Fs02** [go-rel/rel#102]
https://github.com/denisenkom/go-mssqldb or other driver

Example: https://github.com/go-rel/rel/tree/master/adapter/sqlite3

**Comment by ganesh292** [comment]
Hello Team. I would be happy to take this up but I need some guidance as to what is the config required for mssql adapter? Thanks

**Comment by Fs02** [comment]
That's depends on the database, it's what you supposed t figure out, you can see other adapter for reference

**Comment by Fs02** [comment]
Initial version for MS SQL Adapter available here: https://github.com/go-rel/mssql
