### ISSUE TITLE
[Subquery?] How to query user in any of groups.

### ISSUE THREAD

**Issue by xpol** [go-rel/rel#135]
```
table User {
  id int
  name varchar(32)
}

table GroupUser struct {
  user_id int
  group_id int
}

table Group {
  id int
  name varchar(32)
}
```

How to find unique user in groups [1,2,3] ?
Follow code does not work:

```go
groups := []int{1,2,3}
subQuery := rel.From("group_users").Select("DISTINCT user_id").Where(where.InInt("group_id", groups))
repo.FindAll(ctx, &users, where.In("id",  subQuery))
```

**Comment by Fs02** [comment]
There's a function for Distinct in query builder, I think what you want to do is this?

```go
groups := []int{1,2,3}
subQuery := rel.From("group_users").Select("user_id").Distinct().Where(where.InInt("group_id", groups))
repo.FindAll(ctx, &users, where.In("id",  subQuery))
```

**Comment by xpol** [comment]
The problem is not how to build the subquery.
The problem is `where.In` does not allow second argument to be type`rel.Query`.

> SELECT * FROM `users` WHERE `id` IN (?); - sql: converting argument $1 type: unsupported type rel.Query, a struct

**Comment by Fs02** [comment]
ah, sorry I miss understood the last line.
REL currently doesn't supports subquery in the query builder. alternatively, you can:

- Performs two separate query.
- Use `where.Fragment` to specify the subquery in where condition.
- Write raw sql using `rel.SQL`.

**Comment by xpol** [comment]
It seems where.Fragment does not support slice of ids (int/sting).
```go
repo.FindAll(ctx, &users, where. Fragment("id IN (SELECT user_id FROM group_users WHERE group_id IN (?))", groups))
```

```
SELECT * FROM `users` WHERE id IN (SELECT user_id FROM group_users WHERE group_id IN (?)); - sql: converting argument $1 type: unsupported type []string, a slice of string
panic: sql: converting argument $1 type: unsupported type []string, a slice of string
```

**Comment by Fs02** [comment]
yes it doesn't, fragment is only a way to specify fragment of raw query, it doesn't support parsing and expanding the query parameters
feel free to create a pr if you need this feature 😄

**Comment by xpol** [comment]
How about write a `where.FragmentIn` family helpers？

**Comment by Fs02** [comment]
any design of the example usage?

**Comment by xpol** [comment]
I read the code, `where.FragmentIn` is not a good idea.

Is it possible to change `Builder.buildInclusion()` detect if the **only one** argument is `rel.Query`.
If true, render that arguement first and place it between the `IN (` and `)`.

**Comment by Fs02** [comment]
Can you elaborate more? I don't think it'll work

**Comment by xpol** [comment]
#136 Fix this.
