### ISSUE TITLE
Support smallint type for db migration

### ISSUE THREAD

**Issue by ahsanulks** [go-rel/rel#143]
https://github.com/go-rel/rel/blob/master/column.go#L6

no support for small int. Can I add it?

**Comment by Fs02** [comment]
of course, feel free to send a pull request 👍

**Comment by ahsanulks** [comment]
already add it on https://github.com/go-rel/rel/pull/144

**Comment by Fs02** [comment]
Released as v0.10.0: https://github.com/go-rel/rel/releases/tag/v0.10.0
Thank you
