### ISSUE TITLE
How to work with insert operations, relations have any examples?

### ISSUE THREAD

**Issue by ealoshinsky** [go-rel/rel#175]
Hello, I'm learned documentation but not understand how it work insert operation, see down my short example. 

```Golang
// we have next migrations
func MigrateCreateProfile(schema *rel.Schema) {
	schema.CreateTable("profile", func(t *rel.Table) {
		t.ID("id")
		t.String("middle_name")
		t.String("first_name")
		t.String("last_name")
	})
}

func MigrateCreateUser(schema *rel.Schema) {
	schema.CreateTable("users", func(t *rel.Table) {
		t.ID("id")
		t.String("email", rel.Unique(true), rel.Required(true))
		t.String("phone", rel.Unique(true))
		t.String("password", rel.Required(true))
		t.DateTime("joined_at", rel.Default(time.Now()))
		t.Int("profile", rel.Unique(true))

		t.ForeignKey("profile", "profile", "id")
	})
}

// and next code for mapping tables to struct 
type User struct {
	ID       int
	Email    string
	Phone    string
	Password string
	JoinedAt time.Time
	Profile  *Profile `auto:"true"`
}

type Profile struct {
	ID         int
	FirstName  string
	MiddleName string
	LastName   string
}
// and next code for insert user into table.
func Save(ctx context.Context, record interface{}) error {
	fmt.Printf("%#v", record)
	return r.repository.Transaction(ctx, func(ctx context.Context) error {
		return r.repository.Insert(ctx, record)
	})
}
```

From  docs after this code must created new record in Profile table and new record in Users, what's wrong in my code.

May be do you have any example code, about relation and CRUD operations using go-rel?

**Comment by Fs02** [comment]
Hi,

Looks like your association definition is incorrect:
- `t.Int("profile", rel.Unique(true))` is supposed to be foreign key right? then I think the field name should be other than `profile`, maybe `profile_id` (example: https://github.com/Fs02/go-todo-backend/blob/718e1ef75660dc17383a29ccb5eea274b000c461/db/migrations/20203006230700_create_points.go#L15-L17)
- `Profile  *Profile `auto:"true"`` is missing `ProfileID Int` field
