### ISSUE TITLE
Iterator + Preload ?

### ISSUE THREAD

**Issue by ddanurwenda** [go-rel/rel#176]
Hi, I have this scenario where I need to load millions of record and its association. Currently I'm using preload after `.Next()` of Iterator, and I'm afraid I'd fall into n+1 query. Is there a better workaround, or is it inevitable?

**Comment by Fs02** [comment]
Hi, Thanks for using REL

Ah right, this feature is currently missing

From API perspective, it's possible to implement something like this:
```go
    iter = repo.Iterate(ctx, rel.From("users").Preload("addresses"), rel.BatchSize(500))
```
but the [implementation](https://github.com/go-rel/rel/blob/64971a9742b36cf2d4cdee452df7f6266f2be8a0/iterator.go#L74-L92) is not that simple

a workaround is maybe to manually iterate using `FindAll` method.

**Comment by ddanurwenda** [comment]
i see.. I think we need additional example on Preload documentation expressing that it accepts slice as well. All variables in current documentation only expressing singular value (`&transaction`, `&user`..)

Thanks for the direction though, will use that for now.

**Comment by Fs02** [comment]
Ah right, will update the document examples later, Thanks!
