### ISSUE TITLE
[question] repo.Instrumentation how to passed on context?

### ISSUE THREAD

**Issue by fifsky** [go-rel/rel#182]
I am using go.opentelemetry.io/otel to record trace, but i can't be passed on context

```
// database trace
repo.Instrumentation(func(ctx context.Context, op string, message string) func(err error) {
span := trace.SpanFromContext(ctx)

if span.IsRecording()  {  //  Only the first transmission from the external can be recorded
	ctx, span = dbTracer.Start( // The ctx here can't be passed on ??
		ctx,
		op,
		trace.WithSpanKind(trace.SpanKindServer),
	)

	span.SetAttributes(
		attribute.String("db.sql", message),
	)
}

return func(err error) {
	if err != nil {
		span.RecordError(err)
		span.SetStatus(codes.Error, err.Error())
	}
	span.End()
	log.Printf("[SQL] operation:%s query:%s", op, message)
}
})
```

Maybe  reutrn ctx, func(err error)

**Comment by Fs02** [comment]
if I understand the problem correctly, the span between parent span can't be processed correctly because context is not passed?

> Maybe reutrn ctx, func(err error)

hmm, I think this is the only solution, but it will require a lot of code changes
(I'll be happy if you can help open a pull request for this)

**Comment by fifsky** [comment]
@Fs02 
Thanks for your reply, I need some time to get familiar with the code, if I achieve it, I will submit PR
