### ISSUE TITLE
Add option for filtered/conditional index option

### ISSUE THREAD

**Issue by lafriks** [go-rel/rel#218]
Add option that implements `rel.KeyOption` for index WHERE condition.

As far as I know only MySQL does not support this.

PostgreSQL: https://www.postgresql.org/docs/9.1/sql-createindex.html
SQLite3: https://www.sqlite.org/partialindex.html
MSSQL: https://docs.microsoft.com/en-us/sql/t-sql/statements/create-index-transact-sql?view=sql-server-ver15

so that it could be specified for example:

```go
t.Unique([]string{"column"}, rel.KeyCondition("NOT deleted"))
```

That would generate:

```sql
CREATE UNIQUE INDEX ON table (column) WHERE NOT deleted;
```

technically this could be easily done by simple type but I don't know how to implement this conditionally so not to break MySQL provider that does not support this

```go
// KeyCondition filter option for unique key.
type KeyCondition string

func (kc KeyCondition) applyKey(key *Key) {
	key.Options += fmt.Sprintf(" WHERE (%s)", kc)
}
```

**Comment by Fs02** [comment]
> so that it could be specified for example:
> 
> ```go
> t.Unique([]string{"column"}, rel.KeyCondition("NOT deleted"))
> ```

Another alternative is to implement `applyKey(key *Key)` to FilterQuery, so we can specify the condition as something like this:

```go
t.Unique([]string{"date"}, where.Lt("date", "2020-10-10"))
```

what do you think?

> As far as I know only MySQL does not support this.

as for mysql, I think we can just log a warning message or maybe throw panic for unsupported option.

Anyway, I think this is a very nice addition to have 🎉 , let me know if you are interested to implement this!

**Comment by lafriks** [comment]
Yes, that would be nice to reuse filter query for this. Looking at the code I could not find a way to not apply this for mysql and just log warning. If you could point out a hint on how to do that I could implement that

**Comment by Fs02** [comment]
Actually that package is deprecated, now adapters already extracted to different repo:
- https://github.com/go-rel/sql (for shared adapter codes)
- https://github.com/go-rel/sqllite3
- https://github.com/go-rel/mysql
- https://github.com/go-rel/mssql

so in this case, maybe you can add the option here: https://github.com/go-rel/sql/blob/e49d9c759b8dc5f314ebef8b42cd27c5043648b6/builder/index.go#L8-L11 
and configure it here: https://github.com/go-rel/mysql/blob/c9cd49f4c5fd0a3692476787dd1c9d58eec1a55a/mysql.go#L38

sorry that you have to send pr to multiple repos 🙈

**Comment by lafriks** [comment]
ok, will try to implement this

**Comment by lafriks** [comment]
When last to adapter changes are merged this will be done :)
