### ISSUE TITLE
Soft-delete query condition should prefix column with table name

### ISSUE THREAD

**Issue by lafriks** [go-rel/rel#233]
If using rel to query record:
```go
group := &store.DeviceGroup{}
err := s.db.Find(ctx, group, rel.Join("clients").Where(rel.And(rel.Eq("device_groups.id", id), rel.Eq("clients.id", clientID))))
```

and both tables have soft-delete columns rel would generate query that will fail with error:
```
time="2021-10-19T19:52:09+03:00" level=error msg=Query args="[2 1dfb4a1b-78c7-45a6-bc02-31d05906f111 false]" err="ERROR: column reference \"deleted\" is ambiguous (SQLSTATE 42702)" pid=1082 sql="SELECT * FROM \"device_groups\" JOIN \"clients\" ON \"device_groups\".\"client_id\"=\"clients\".\"id\" WHERE (\"device_groups\".\"id\"=$1 AND \"clients\".\"id\"=$2 AND \"deleted\"=$3) LIMIT 1;"
```

soft-delete condition should be added with table name ex. `AND "device_groups"."deleted"=$3`

**Comment by Fs02** [comment]
Thanks for your awesome works ❤️ 

`github.com/go-rel/sql` v0.3.0 has been released: https://github.com/go-rel/sqlite3/releases/tag/v0.3.0
will release adapters as soon as `dependabot` submitted dependency upgrade pr

**Comment by lafriks** [comment]
I will probably still push to my own forks, I'm just used to work that way also on other OSS projects I work on :)

You could probably add me rights to add labels for issues/PRs
