### ISSUE TITLE
Non-returning insert statements

### ISSUE THREAD

**Issue by talkanbaev-artur** [go-rel/rel#252]
Hi! Thank you for the amazing library - I have been really enjoying it so far!

The issues is following - the insert query builder assumes that the primary key is never inserted, but *generated*, and attaches `RETURNING` statement to every insert query. 

The point is - I wanted to reproduce the table with UUID primary key, and the key being generated on the go side - just want to insert both data and primary key. Currently, the primary key policy for the builder is either to consume a primary key name and attach returning statement, or to panic (if no primary key specified). Specifically I talk about [this function](https://github.com/go-rel/rel/blob/30b6827eedcae0ae5eab2bc412552df5432fd709/adapter/sql/builder.go#L811), which always sets the value because of [this function's behaviour](https://github.com/go-rel/rel/blob/30b6827eedcae0ae5eab2bc412552df5432fd709/document.go#L93). Therefore, [this](https://github.com/go-rel/rel/blob/30b6827eedcae0ae5eab2bc412552df5432fd709/adapter/sql/builder.go#L381) branch is always executed.

I know these are not standard practices, however, it might be an interesting idea to add support for them. And so far I have not found a logical solution to this problem, and it seems that there should be a discussion on it.

Thank you for all!

**Comment by Fs02** [comment]
Hi! Thanks for using REL 😄 

can you share your struct? Maybe you forgot to add primary tag like in this example?
https://go-rel.github.io/basics/#primary-key

https://github.com/go-rel/rel/blob/30b6827eedcae0ae5eab2bc412552df5432fd709/document.go#L93
This function is also called when updating or deleting record

**Comment by talkanbaev-artur** [comment]
Hi!

No, it seems, that for custom defined types, I had to manually add `IsZero()` method tho handle zero checks. The UUID package that I used represented the id in `[16]byte` form and could not implicitly get the correct value. Hence, the structset skipped the uuid field. When I switched back to the string, the query worked perfectly. Thanks! Guess the issues was in the custom type handling. 

Sorry for disturbance.

**Comment by Fs02** [comment]
Hi!

no problem, can you share the package you use? Maybe it can be a future improvement

**Comment by talkanbaev-artur** [comment]
Hi! Sure, here it is:
https://github.com/google/uuid

**Comment by Fs02** [comment]
Looks like it’s unimplememted feature 🤔 
https://github.com/go-rel/rel/blob/30b6827eedcae0ae5eab2bc412552df5432fd709/document.go#L445

**Comment by Fs02** [comment]
Thanks for the report, your investigation was correct
isZero doesn't handle [16]byte properly, opened a fix here https://github.com/go-rel/rel/pull/253

**Comment by Fs02** [comment]
fix released, now you should be able to use `uuid.UUID` directly in your struct, thanks
https://github.com/go-rel/rel/releases/tag/v0.29.2
