### ISSUE TITLE
adapter package is missing in v0.30.0

### ISSUE THREAD

**Issue by nikolaistraessle** [go-rel/rel#260]
Hi guys

The adapter package is missing in the version v0.30.0.

```
fieldforce/src/server imports
        github.com/go-rel/rel/adapter/mysql: module github.com/go-rel/rel@latest found (v0.30.0), but does not contain package github.com/go-rel/rel/adapter/mysql
```

The package is also not available in the source code on tag v0.30.0.

Is there a special reason, why this package was removed?
If not, is it possible to readd this package for newer versions.

Many thanks and BR

**Comment by lafriks** [comment]
It is moved to separate package `github.com/go-rel/mysql`
