### ISSUE TITLE
How implement "Insert Ignore" in go-rel ?

### ISSUE THREAD

**Issue by hxgdzyuyi** [go-rel/rel#268]
I couldn't find a way to add Ignore

For example

```mysql
INSERT IGNORE INTO A/B/C/.. ... ...
```

I am wondering if anybody has experience with Insert Ignore in go-rel. Thanks!

**Comment by Fs02** [comment]
Hi,

`INSERT IGNORE` is not supported in REL yet.

is your use case can be covered if using `ON DUPLICATE KEY UPDATE`? https://github.com/go-rel/rel/issues/217
if yes, maybe I can start taking a look at that issue this weekend

**Comment by Fs02** [comment]
released in v0.33.1
can you try it and let me know if there's any bug? thanks 

example:
```go
repo.Insert(ctx, &user, rel.OnConflictIgnore())
// or
repo.InsertAll(ctx, &users, rel.OnConflictIgnore())
```

**Comment by hxgdzyuyi** [comment]
> 

thanks !

**Comment by hxgdzyuyi** [comment]
it's work
