### ISSUE TITLE
Macro rendering error on https://go-rel.github.io/reference/rel/

### ISSUE THREAD

**Issue by fredrikatmainspringenergy** [go-rel/rel#321]
<img width="1496" alt="Screen Shot 2022-10-28 at 2 19 37 PM" src="https://user-images.githubusercontent.com/77465869/198734786-375d6897-c4f9-4ef3-81b3-cf5ca80f7670.png">

**Comment by Fs02** [comment]
should be fixed now https://github.com/go-rel/doc/pull/72
