### ISSUE TITLE
Data types

### ISSUE THREAD

**Issue by fairking** [go-rel/rel#332]
I could not find any [documentation](https://go-rel.github.io/introduction/) about what are data types supported by `rel` as column types.
Is there any "decimal" support. I would like to have a column "Quantity" which is a number with 5 decimal points.
I also would need 2 decimal points for money representation. Many suggestions are to use integers, but I would like to check are there any alternatives.

I wish there is some documentation which states which types are supported and can be used in rel entities.

**Comment by Fs02** [comment]
you can use any types as long as it's supported by the db driver you use, you can also implement your own custom Scanner and Valuer interface
