### ISSUE TITLE
millisecond is not saved on db

### ISSUE THREAD

**Issue by rifqi-ridwan** [go-rel/rel#374]
after take a look, is this intentionally to be set without milliseconds? why?
https://github.com/go-rel/rel/blob/6c3495d2f4128b45e5d576ee72d6f715eb0b19cc/structset.go#L8-L12

**Comment by Fs02** [comment]
it's for unit testing purpose
you can override that function to get milliseconds: https://github.com/go-rel/rel/pull/201

**Comment by rifqi-ridwan** [comment]
override it by manually handling it when insert or update is it right?

**Comment by Fs02** [comment]
you only need to do it once, for example from init function

**Comment by rifqi-ridwan** [comment]
you're right
if anyone come here and looking for an answer, this is how to solve it
```
func init() {
	rel.Now = time.Now
}
```
