### ISSUE TITLE
godoc on struct methods not on interface methods

### ISSUE THREAD

**Issue by mhewedy** [go-rel/rel#92]
I am starting using rel in some side project, Mostly I like it. (I have some catches, might open issues for later).

But for now, I want to mention what important thing and that is the godc doesn't appear in the IDE (I use IntelliJ with Goland plugin)

This is because the documentation is on the struct method no on the Repository interface methods, which make it harder to learn about the individual methods.

This popup shows no godoc here:
![Screen Shot 2020-09-04 at 3 17 58 AM](https://user-images.githubusercontent.com/1086049/92185727-56920200-ee5d-11ea-98f3-7da774579d12.png)

I have to navigate to the repository struct impl:
![Screen Shot 2020-09-04 at 3 18 09 AM](https://user-images.githubusercontent.com/1086049/92185739-5d207980-ee5d-11ea-905f-662574676557.png)

And here the only way to find the godoc:
![Screen Shot 2020-09-04 at 3 18 15 AM](https://user-images.githubusercontent.com/1086049/92185744-5e51a680-ee5d-11ea-956c-7b4136c9ef72.png)

**Comment by Fs02** [comment]
Hi, thanks for noticing this issue. I'll add this to `TODO` so we can work on this later.
Let me know if you are thinking to take this task 😄

**Comment by mhewedy** [comment]
> Hi, thanks for noticing this issue. I'm adding this to `TODO` so we can work on this later.
> Let me know if you are thinking to take this task 😄

Yes sure I can work on it. 😊

**Comment by Fs02** [comment]
Thank you, looking forward for your PR 😄

**Comment by Fs02** [comment]
fixed on next release
