### ISSUE TITLE
Has column alias in rel.Select

### ISSUE THREAD

**Issue by mhewedy** [go-rel/rel#93]
I like the `Select` way for writing queries, it provides a good DSL, so I use it to write a semi-complex query instead of the `SQL` function.

But it seems it doesn't handle the column alias properly:

https://github.com/Fs02/rel/blob/3af9e733867dc779d166d97e05a6cc91b369cd13/adapter/sql/util.go#L27

My code looks like:
```
query := Select(col+"col", "round((count(*)::float / (select count(*) / 100 from apartments))::numeric, 0) ratio").
.....
```

And generate SQL is:
```
SELECT "beds as col",roun .....
```

So is there a chance you make the `Escape` function alias-aware?

**Comment by mhewedy** [comment]
What I am trying to achieve is to have a 10+ query results maps to the same struct as the result for all of them comes in the form of col and ratio, and I feel I don't want to build 10 different structs.

**Comment by Fs02** [comment]
Hi, thanks again for noticing this issue. Yes, column alias is not handled currently, I'll add this to TODO.

for a temporary work around, you may add `^` prefix to disable escaping, and escape your query manually, for example:

```go
query := Select("^`bed` as `col`").
```

**Comment by Fs02** [comment]
To summary, I think in this issue we only need to add support for this cases:
- `field as name`
- `table.field as name`

for more complex query, I think it's better if we disable escaping explicitly (`^`) and manually escape it, to prevent potential sql injection for unsanitized input.
